# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  destroy_env:
    description: Destroy a cfn stack
    steps:
      - run:
          command: |
            aws cloudformation delete-stack --stack-name rollback
  

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy cfn stack
          command: |
            aws cloudformation deploy \
            --template-body ec2_simple.yml \
            --stack-name rollback
      - destroy_env
        when: on_fail

workflows:
  cci_workflow:
    jobs:
      - smoke_test